const {
  getCardSets,
  getStructureDeckSets,
} = require("./getCardsMissingForStructureDecks");
const axios = require("axios");
const fs = require("fs");
const { Promise } = require("bluebird");
const _ = require("lodash");

const getCardsInStructureDeck = async (structureDeckName) => {
  const result = await axios
    .get(
      `https://db.ygoprodeck.com/api/v7/cardinfo.php?cardset=${structureDeckName}`
    )
    .catch((e) => {
      // console.error(e);
    });

  return (result && result.data && result.data.data) || null;
};

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

const legendaryHeroDeck = {
  date: "2018-10-04",
  deck: "Legendary Hero Decks - HERO",
  cards: [
    "Xtra HERO Dread Decimator",
    "Destiny HERO - Dogma",
    "Destiny HERO - Plasma",
    "Destiny HERO - Dreadmaster",
    "Destiny HERO - Malicious",
    "Destiny HERO - Celestial",
    "Destiny HERO - Diamond Dude",
    "Destiny HERO - Dread Servant",
    "Destiny HERO - Disk Commander",
    "Destiny HERO - Dark Angel",
    "Destiny HERO - Dynatag",
    "Destiny HERO - Drilldark",
    "Destiny HERO - Decider",
    "Destiny HERO - Dreamer",
    "D Cubed",
    "Elemental HERO Shadow Mist",
    "Elemental HERO Blazeman",
    "Destiny Draw",
    "Over Destiny",
    "Clock Tower Prison",
    "Dark City",
    "Mask Change",
    "Polymerization",
    "Monster Reborn",
    "Magical Stone Excavation",
    "Terraforming",
    "A Feather of the Phoenix",
    "Destiny Signal",
    "D - Time",
    "Eternal Dread",
    "D-Fusion",
    "Destiny End Dragoon",
    "Destiny HERO - Dusktopia",
    "Destiny HERO - Dystopia",
    "Destiny HERO - Dangerous",
    "Masked HERO Dark Law",
    "Masked HERO Anki",
    "Xtra HERO Wonder Driver",
  ],
};

const legendaryAesirDeck = {
  date: "2018-10-04",
  deck: "Legendary Hero Decks - Aesir",
  cards: [
    "Gullveig of the Nordic Ascendant",
    "Tanngrisnir of the Nordic Beasts",
    "Tanngnjostr of the Nordic Beasts",
    "Garmr of the Nordic Beasts",
    "Guldfaxe of the Nordic Beasts",
    "Dverg of the Nordic Alfar",
    "Ljosalf of the Nordic Alfar",
    "Svartalf of the Nordic Alfar",
    "Mara of the Nordic Alfar",
    "Mimir of the Nordic Ascendant",
    "Valkyrie of the Nordic Ascendant",
    "Vanadis of the Nordic Ascendant",
    "Tyr of the Nordic Champions",
    "The Nordic Lights",
    "Nordic Relic Draupnir",
    "March Towards Ragnarok",
    "Forbidden Chalice",
    "Forbidden Lance",
    "Forbidden Dress",
    "Monster Reborn",
    "Soul Charge",
    "Dark Hole",
    "Hey, Trunade!",
    "Mystical Space Typhoon",
    "Gleipnir, the Fetters of Fenrir",
    "Nordic Relic Brisingamen",
    "Nordic Relic Laevateinn",
    "Nordic Relic Gungnir",
    "Nordic Relic Megingjord",
    "Solemn Authority",
    "Thor, Lord of the Aesir",
    "Loki, Lord of the Aesir",
    "Odin, Father of the Aesir",
    "Leo, the Keeper of the Sacred Tree",
    "Ascension Sky Dragon",
    "Beelzeus of the Diabolic Dragons",
    "Beelze of the Diabolic Dragons",
    "Scrap Dragon",
    "Coral Dragon",
  ],
};

const legendaryPKDeck = {
  date: "2018-10-04",
  deck: "Legendary Hero Decks - Phantom Knights",
  cards: [
    "The Phantom Knights of Rusty Bardiche",
    "The Phantom Knights of Ancient Cloak",
    "The Phantom Knights of Silent Boots",
    "The Phantom Knights of Ragged Gloves",
    "The Phantom Knights of Cloven Helm",
    "The Phantom Knights of Fragile Armor",
    "Armageddon Knight",
    "Blue Mountain Butterspy",
    "Rescue Ferret",
    "Junk Forward",
    "Kagemucha Knight",
    "Cockadoodledoo",
    "Effect Veiler",
    "The Phantom Knights' Rank-Up-Magic Launch",
    "Phantom Knights' Spear",
    "Dark Hole",
    "Monster Reborn",
    "Foolish Burial",
    "Reinforcement of the Army",
    "Dark Eruption",
    "Twin Twisters",
    "Phantom Knights' Fog Blade",
    "Phantom Knights' Sword",
    "Phantom Knights' Wing",
    "The Phantom Knights of Shadow Veil",
    "The Phantom Knights of Shade Brigandine",
    "The Phantom Knights of Dark Gauntlets",
    "The Phantom Knights of Tomb Shield",
    "The Phantom Knights of Lost Vambrace",
    "The Phantom Knights of Wrong Magnetring",
    "The Phantom Knights of Mist Claws",
    "The Phantom Knights of Break Sword",
    "The Phantom Knights of Cursed Javelin",
    "Dark Rebellion Xyz Dragon",
    "Dark Requiem Xyz Dragon",
    "Evilswarm Nightmare",
    "Evilswarm Thanatos",
    "Number 86: Heroic Champion - Rhongomyniad",
    "Leviair the Sea Dragon",
    "Dante, Traveler of the Burning Abyss",
  ],
};

const legendaryYuseiDeck = {
  date: "2025-11-06",
  deck: "Legendary 5D's Decks - Yusei",
  cards: [
    "Full-Speed Warrior",
    "Anchorbolt Hedgehog",
    "Crossroad Sonic Chick",
    "Scrap Synchron",
    "Synchro Fellowship",
    "One-Way Synchro",
    "Junk Synchron",
    "Wheel Synchron",
    "Stardust Synchron",
    "Revolution Synchron",
    "Satellite Synchron",
    "Assault Synchron",
    "Jet Synchron",
    "Junk Converter",
    "Doppelwarrior",
    "Effect Veiler",
    "Ash Blossom & Joyous Spring",
    "Mulcharmy Purulia",
    "On Your Mark, Get Set, DUEL!",
    "Tuning",
    "Duelist Genesis",
    "Synchro Rumble",
    "Clashing Souls",
    "Scrap Fist",
    "One for One",
    "Scrapyard",
    "Called by the Grave",
    "Crossout Designator",
    "Forbidden Droplet",
    "Synchro Zone",
    "Infinite Impermanence",
    "Junk Warrior Extreme",
    "Scrap Warrior",
    "Junk Warrior (alternate artwork)",
    "Junk Speeder",
    "Stardust Dragon",
    "Accel Synchro Stardust Dragon",
    "Formula Synchron",
    "Stardust Warrior",
    "Shooting Star Dragon",
    "Crimson Dragon",
  ],
};

const legendaryAkizaDeck = {
  date: "2025-11-06",
  deck: "Legendary 5D's Decks - Akiza",
  cards: [
    "Lonefire Blossom",
    "Witch of the Black Rose",
    "Spore",
    "Rose Lover",
    "Blue Rose Dragon",
    "Ghost Ogre & Snow Rabbit",
    "Red Rose Dragon",
    "White Rose Dragon",
    "Ghost Sister & Spooky Dogwood",
    "Rose Princess",
    "Rose Girl",
    "Roxrose Dragon",
    "Ruddy Rose Witch",
    "Mulcharmy Meowls",
    "Monster Reborn",
    "Terraforming",
    "Miracle Fertilizer",
    "Black Garden",
    "Fragrance Storm",
    "Thorn of Malice",
    "Frozen Rose",
    "White Rose Cloister",
    "Basal Rose Shoot",
    "Infinite Impermanence",
    "Blooming of the Darkest Rose",
    "Black Rose Dragon",
    "Splendid Rose",
    "Black Rose Moonlight Dragon",
    "Garden Rose Maiden",
    "Crossrose Dragon",
    "Periallis, Empress of Blossoms",
    "Ruddy Rose Dragon",
    "Garden Rose Flora",
  ],
};

const legendaryCrowDeck = {
  date: "2025-11-06",
  deck: "Legendary 5D's Decks - Crow",
  cards: [
    "Blackwing - Gale the Whirlwind",
    "Blackwing - Bora the Spear",
    "Blackwing - Vayu the Emblem of Honor",
    "Droll & Lock Bird",
    "Blackwing - Kris the Crack of Dawn",
    "Blackwing - Sharnga the Waning Moon",
    "Blackwing - Oroshi the Squall",
    "Blackwing - Harmattan the Dust",
    "Ash Blossom & Joyous Spring",
    "Blackwing - Simoon the Poison Wind",
    "Ghost Mourner & Moonlit Chill",
    "Blackwing - Vata the Emblem of Wandering",
    "Blackwing - Shamal the Sandstorm",
    "Blackwing - Chinook the Snow Blast",
    "Blackwing - Sudri the Phantom Glimmer",
    "Mulcharmy Fuwalos",
    "Mystical Space Typhoon",
    "Book of Moon",
    "Black Whirlwind",
    "Forbidden Chalice",
    "Called by the Grave",
    "Black Feather Whirlwind",
    "Icarus Attack",
    "Delta Crow - Anti Reverse",
    "Blackbird Close",
    "Blackwing - Twin Shadow",
    "Blackwing Armor Master",
    "Blackwing Armed Wing",
    "Blackwing - Silverwind the Ascendant",
    "Black-Winged Dragon",
    "Blackwing - Nothung the Starlight",
    "Blackwing Full Armor Master",
    "Black-Winged Assault Dragon",
    "Blackwing - Boreastorm the Wicked Wind",
  ],
};

const chroniclesFallenAndVirtuous = {
  date: "2025-10-23",
  deck: "THE CHRONICLES DECK: The Fallen & The Virtuous",
  cards: [
    "Alba-Lenatus the Abyss Dragon",
    "Albion the Branded Dragon",
    "Albion the Shrouded Dragon",
    "Aluber the Jester of Despia",
    "Blazing Cartesia, the Virtuous",
    "Branded Banishment",
    "Branded Beast",
    "Branded Bond",
    "Branded Fusion",
    "Branded in High Spirits",
    "Branded in Red",
    "Branded in White",
    "Branded Lost",
    "Branded Opening",
    "Branded Regained",
    "Branded Retribution",
    "Branded Sword",
    "Brigrand the Glory Dragon",
    "Bystial Druiswurm",
    "Bystial Magnamhut",
    "Bystial Saronir",
    "Despian Tragedy",
    "Dogmatika Ecclesia, the Virtuous",
    "Dogmatika Fleurdelis, the Knighted",
    "Dogmatika Maximus",
    "Dogmatika Punishment",
    "Fallen of Albaz",
    "Foolish Burial",
    "Fusion Deployment",
    "Fusion Duplication",
    "Gold Sarcophagus",
    "Granguignol the Dusk Dragon",
    "Guiding Quem, the Virtuous",
    "Incredible Ecclesia, the Virtuous",
    "Keeper of Dragon Magic",
    "Lubellion the Searing Dragon",
    "Mirrorjade the Iceblade Dragon",
    "Nadir Servant",
    "Nibiru, the Primal Being",
    "Rindbrumm the Striking Dragon",
    "Sprind the Irondash Dragon",
    "Springans Kitt",
    "Super Polymerization",
    "The Black Goat Laughs",
    "The Bystial Lubellion",
    "The Fallen & The Virtuous",
    "The Stigmata-Devouring Dragon",
    "Titaniklad the Ash Dragon",
    "Tri-Brigade Mercourier",
    "Triple Tactics Thrust",
  ],
};

const mainFunction = async () => {
  const cardSets = await getCardSets();
  console.log(`There are ${cardSets.length} sets`);

  const structureDeckSets = getStructureDeckSets(cardSets);
  console.log(`There are ${structureDeckSets.length} structure decks`);

  const cardsInStructureDeckSet = [
    legendaryAesirDeck,
    legendaryHeroDeck,
    legendaryPKDeck,
    legendaryAkizaDeck,
    legendaryCrowDeck,
    legendaryYuseiDeck,
    chroniclesFallenAndVirtuous,
  ];
  await Promise.each(structureDeckSets, async ({ deck, date }) => {
    const cardsInStructureDeck = await getCardsInStructureDeck(deck);
    const cardNames = cardsInStructureDeck.map((card) => card["name"]);
    cardsInStructureDeckSet.push({ deck, cards: cardNames, date });
    console.log(`Downloaded ${cardsInStructureDeck.length} cards for ${deck}`);
    await sleep(100);
  });

  // TODO: Replace fs.writeFile with fs.writeFileSync for consistency
  fs.writeFile(
    "./structureDecks/cardsInStructureDecks.json",
    JSON.stringify(_.sortBy(cardsInStructureDeckSet, ["date"]), null, 3),
    function (err) {
      // console.error(err);
    }
  );
};

mainFunction();
